#cloud-config
package_update: true
package_upgrade: true

packages:
  - base-devel
  - git
  - go
  - openssh
  - qemu-user-agent

runcmd:
  - systemctl enable --now sshd
  - systemctl enable --now qemu-user-agent
