#cloud-config
ssh_pwauth: true
bootcmd:
  - sed -i '/community/s/^#//' /etc/apk/repositories
  - apk update
package_update: true
package_upgrade: true
packages:
  - alpine-sdk
  - go
  - sudo
  - openssh
  - rsync
runcmd:
  - adduser artisan sudo || true
  - rc-update add sshd default
  - rc-service sshd start || true
