# /etc/dnsmasq.d/eggslab/20-hosts.conf
# -------------------------------------------------------------------------
# KIT DI PRONTO SOCCORSO (In caso di IP incastrati o conflitti SDN)
# 1. Svuota il registro di sistema:  sudo truncate -s 0 /etc/dnsmasq.d/eggslab/ethers
# 2. Pulisci la memoria dei lease:   sudo rm /var/lib/misc/dnsmasq.eggslab.leases
# 3. Riavvia il motore dnsmasq:      sudo systemctl restart dnsmasq@eggslab.service
# Ricordati di aggiungere sudo ip route add 10.99.0.0/24 via 192.168.1.2
# -------------------------------------------------------------------------

dhcp-host=BC:24:11:00:02:01,10.99.0.201,forge-alpine
dhcp-host=BC:24:11:00:02:02,10.99.0.202,forge-arch
dhcp-host=BC:24:11:00:02:03,10.99.0.203,forge-debian
dhcp-host=BC:24:11:00:02:04,10.99.0.204,forge-devuan
dhcp-host=BC:24:11:00:02:05,10.99.0.205,forge-fedora
dhcp-host=BC:24:11:00:02:06,10.99.0.206,forge-manjaro
dhcp-host=BC:24:11:00:02:07,10.99.0.207,forge-opensuse
dhcp-host=BC:24:11:00:02:08,10.99.0.208,forge-ubuntu